### PR TITLE
Added CSS file - basic layout

### PR DESCRIPTION
**Pull request by chrisrowland89**
Added style.css file - basic layout as designed in the wireframe

### CODE REVIEW

**Review by bragabruno — APPROVED** [review]
looks good to me.

**Comment by laughingman-hass** [comment]
Also adding, current the CSS mainly addresses the layout of the pages.
- [ ] Additionally should add some consistent styling across the pages.

**Comment by laughingman-hass** [comment]
- [ ] Add a link to Home in the nav bar

**Comment by laughingman-hass** [comment]
I've used [Prettier](https://prettier.io/) to auto-format the html. It's an opinionated formatter, and is pretty much the standard now. Very much recommend to add this has a toolchain. If there is time I'll add it as an npm package so everyone can easily run it.

**Comment by laughingman-hass** [comment]
closing as everything was included in #2

**Pull request closed without merging**
